{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "content-length": "373",
    "sec-ch-ua": "\"Not A(Brand\";v=\"99\", \"Google Chrome\";v=\"121\", \"Chromium\";v=\"121\"",
    "sec-ch-ua-platform": "\"Windows\"",
    "client_id": "3d358a28b3a14607b97f76c675a2d023",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "client_secret": "04724842BbC54bF19C7De3E1902d755b",
    "content-type": "application/json",
    "accept": "*/*",
    "origin": "http://localhost:8081",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8081/console/",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,ta;q=0.6"
  },
  "clientCertificate": null,
  "method": "PUT",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/customers/0",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/customers/0",
  "listenerPath": "/api/*",
  "localAddress": "/127.0.0.1:8081",
  "relativePath": "/api/customers/0",
  "uriParams": {
    "customerid": "0"
  },
  "rawRequestUri": "/api/customers/0",
  "rawRequestPath": "/api/customers/0",
  "remoteAddress": "/127.0.0.1:55749",
  "requestPath": "/api/customers/0"
}